// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[FEATURE-2]
	_ = x[BACKGROUND-3]
	_ = x[SCENARIO-4]
	_ = x[GIVEN-5]
	_ = x[WHEN-6]
	_ = x[THEN-7]
	_ = x[AND-8]
}

const _TokenType_name = "ILLEGALEOFFEATUREBACKGROUNDSCENARIOGIVENWHENTHENAND"

var _TokenType_index = [...]uint8{0, 7, 10, 17, 27, 35, 40, 44, 48, 51}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
